site_name: Still.js Framework
site_url: https://stilljs.dev
nav:
  - WHAT IS Still.js: index.md
  - INSTALLATION: installation-and-running.md
  - GET STARTED: get-start.md
  - COMPONENTS:
      - Fundamentls: components.md
      - Private Components: components-private.md
      - Multi level (3+) nesting: components-nesting-3+.md
  - ROUTING: routing.md
  - STRUCTURE: Still.js Architecture.md
  #- Playground: playground.md
theme:
  name: material
  logo: assets/img/logo.png
  favicon: assets/img/logo-no-bg.ico
  features:
    - navigation.expand
    - navigation.footer
    - content.code.copy

  icon:
    repo: fontawesome/brands/github
  palette:
    #Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light Mode
      primary: blue
      accent: deep orange

    #Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark Mode
      primary: green
      accent: deep purple

extra_css:
  - assets/css/general.css
  - https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.13/codemirror.min.css
  - https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.13/theme/dracula.min.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.13/codemirror.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.13/mode/javascript/javascript.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.13/addon/edit/closebrackets.min.js
  - docs/assets/editor.js

markdown_extensions:
  #Diagrams settings
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  # Tab diagrams
  - pymdownx.tabbed:
      alternate_style: true
#extra:
#  social:
#    - icon: simple/linkedin
#      link: https://www.npmjs.com/settings/stilljs/packages

copyright: Cpyright &copy; 2025 StillJS
